# Generated by Django 6.0.3 on 2026-03-12 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anatomy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mutation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('cost', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(choices=[('physical', 'Physical'), ('physical_defect', 'Physical Defect'), ('mental', 'Mental'), ('mental_defect', 'Mental Defect')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skilltree', models.CharField(choices=[('acrobatics', 'Acrobatics'), ('axe', 'Axe'), ('bow_and_rifle', 'Bow and Rifle'), ('cooking_and_gathering', 'Cooking and Gathering'), ('cudgel', 'Cudgel'), ('customs_and_folklore', 'Customs and Folklore'), ('endurance', 'Endurance'), ('heavy_weapon', 'Heavy Weapon'), ('long_blade', 'Long Blade'), ('multiweapon_fighting', 'Multiweapon Fighting'), ('persuasion', 'Persuasion'), ('physic', 'Physic'), ('pistol', 'Pistol'), ('self_discipline', 'Self-discipline'), ('shield', 'Shield'), ('short_blade', 'Short Blade'), ('single_weapon_fighting', 'Single Weapon Fighting'), ('tactics', 'Tactics'), ('tinkering', 'Tinkering'), ('wayfaring', 'Wayfaring'), ('nonlinearity', 'Nonlinearity')], help_text='The skill tree/category this skill belongs to', max_length=100)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('cost', models.PositiveIntegerField()),
                ('attribute', models.CharField(choices=[('strength', 'Strength'), ('agility', 'Agility'), ('toughness', 'Toughness'), ('willpower', 'Willpower'), ('intelligence', 'Intelligence'), ('ego', 'Ego')], help_text='Primary attribute this skill is associated with', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BodyPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=100, unique=True)),
                ('integral', models.BooleanField(default=False)),
                ('appendage', models.BooleanField(default=False)),
                ('plural', models.BooleanField(default=False)),
                ('mortal', models.BooleanField(default=False)),
                ('branching', models.CharField(choices=[('lateral', 'Lateral'), ('longitudinal', 'Longitudinal'), ('vertical', 'Vertical'), ('stratal', 'Stratal')], default='lateral', help_text='Primary branching direction', max_length=100)),
                ('requires_part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='required_by', to='qud_species_app.bodypart')),
                ('usually_on', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subparts', to='qud_species_app.bodypart')),
            ],
        ),
        migrations.CreateModel(
            name='BodyPartCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=1)),
                ('anatomy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qud_species_app.anatomy')),
                ('body_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qud_species_app.bodypart')),
            ],
            options={
                'unique_together': {('anatomy', 'body_part')},
            },
        ),
        migrations.AddField(
            model_name='anatomy',
            name='parts',
            field=models.ManyToManyField(related_name='anatomies', through='qud_species_app.BodyPartCount', to='qud_species_app.bodypart'),
        ),
        migrations.CreateModel(
            name='Creature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('base_creature', 'Base creature objects'), ('tier_1', 'Tier 1 creatures'), ('tier_2', 'Tier 2 creatures'), ('tier_3', 'Tier 3 creatures'), ('tier_4', 'Tier 4 creatures'), ('tier_5', 'Tier 5 creatures'), ('tier_6', 'Tier 6 creatures'), ('tier_7', 'Tier 7 creatures'), ('tier_8', 'Tier 8 creatures'), ('tier_x', 'Tier X creatures'), ('merchants', 'Merchants'), ('npc', 'NPCs')], max_length=50)),
                ('av', models.IntegerField(blank=True, null=True)),
                ('dv', models.IntegerField(blank=True, null=True)),
                ('hitpoints', models.IntegerField(blank=True, null=True)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('strength', models.IntegerField(blank=True, null=True)),
                ('agility', models.IntegerField(blank=True, null=True)),
                ('toughness', models.IntegerField(blank=True, null=True)),
                ('intelligence', models.IntegerField(blank=True, null=True)),
                ('willpower', models.IntegerField(blank=True, null=True)),
                ('ego', models.IntegerField(blank=True, null=True)),
                ('heat_resistance', models.IntegerField(blank=True, null=True)),
                ('cold_resistance', models.IntegerField(blank=True, null=True)),
                ('electric_resistance', models.IntegerField(blank=True, null=True)),
                ('acid_resistance', models.IntegerField(blank=True, null=True)),
                ('species', models.CharField(blank=True, max_length=50)),
                ('faction', models.CharField(blank=True, max_length=50)),
                ('anatomy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='qud_species_app.anatomy')),
                ('mutations', models.ManyToManyField(blank=True, to='qud_species_app.mutation')),
                ('skills', models.ManyToManyField(blank=True, to='qud_species_app.skill')),
            ],
        ),
    ]
