# Generated by Django 6.0.3 on 2026-03-12 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qud_species_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bodypart',
            name='branching',
        ),
    ]
