# Generated by Django 6.0.3 on 2026-03-13 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qud_species_app', '0002_remove_bodypart_branching'),
    ]

    operations = [
        migrations.AddField(
            model_name='mutation',
            name='internal_name',
            field=models.CharField(default='Hello', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
