# Generated by Django 6.0.3 on 2026-03-13 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qud_species_app', '0003_mutation_internal_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mutation',
            name='type',
            field=models.CharField(choices=[('physical', 'Physical'), ('physical_defect', 'Physical Defect'), ('mental', 'Mental'), ('mental_defect', 'Mental Defect'), ('morphotype', 'Morphotype')], max_length=20),
        ),
    ]
