# Generated by Django 6.0.3 on 2026-03-13 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qud_species_app', '0005_alter_mutation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mutation',
            name='type',
            field=models.CharField(choices=[('morphotypes', 'Morphotypes'), ('physical', 'Physical'), ('physical_defect', 'Physical Defect'), ('mental', 'Mental'), ('mental_defect', 'Mental Defect')], max_length=20),
        ),
    ]
