# Generated by Django 6.0.3 on 2026-03-13 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qud_species_app', '0006_alter_mutation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creature',
            name='agility',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='creature',
            name='ego',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='creature',
            name='intelligence',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='creature',
            name='level',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='creature',
            name='strength',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='creature',
            name='toughness',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='creature',
            name='willpower',
            field=models.CharField(max_length=50),
        ),
    ]
