# Generated by Django 6.0.3 on 2026-03-13 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qud_species_app', '0007_alter_creature_agility_alter_creature_ego_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='internal_name',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
